# Generated by Django 5.1.3 on 2025-05-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payos_order_code",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Mã đơn hàng duy nhất gửi cho PayOS",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payos_payment_link_id",
            field=models.CharField(
                blank=True,
                help_text="ID của link thanh toán từ PayOS",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payos_payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Chờ thanh toán"),
                    ("PAID", "Đã thanh toán"),
                    ("PROCESSING", "Đang xử lý (PayOS)"),
                    ("SUCCESS", "Thành công"),
                    ("FAILED", "Thất bại"),
                    ("CANCELLED", "Đã hủy (PayOS)"),
                    ("EXPIRED", "Đã hết hạn (PayOS)"),
                ],
                default="PENDING",
                max_length=20,
                null=True,
                verbose_name="Trạng thái thanh toán PayOS",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cod", "Thanh toán khi nhận hàng"),
                    ("transfer", "Chuyển khoản ngân hàng (PayOS)"),
                ],
                default="cod",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Chờ thanh toán"),
                    ("pending", "Đang chờ xử lý (COD)"),
                    ("processing", "Đang xử lý"),
                    ("shipped", "Đã giao hàng"),
                    ("delivered", "Đã nhận hàng"),
                    ("cancelled", "Đã hủy"),
                    ("payment_failed", "Thanh toán thất bại"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
